### ISSUE TITLE
"Unable to get vulns for dependencies in 30076ms: timeout"

### ISSUE THREAD

**Issue by jimshowalter** [google/osv.dev#2039] opened 2024-03-10 16:37 UTC
**Describe the bug**
Calls keep timing out, which breaks our parity test.

**To Reproduce**
Call https://google.github.io/osv.dev/post-v1-querybatch.

**Expected behavior**
The API should return vulns instead of timing out.

**Comment by another-rex** [comment] 2024-03-13 00:33
Thanks for letting us know! We are currently looking into this. 

Can you confirm the timeout was happening after 30 seconds, not 60 seconds?

**Comment by jayvdb** [comment] 2024-03-13 01:00
Per https://github.com/google/osv-scanner/issues/856, I am seeing 20+ failures per day in CI, for the last few days, including right now.  Also I can reproduce it locally.

**Comment by another-rex** [comment] 2024-03-13 02:58
The timeout issues should be mitigated now, and we are currently looking at more options for preventing this in the future. Please test it out!

**Comment by jimshowalter** [comment] 2024-03-13 14:43
The most recent parity test passed.

To answer your question about the delay, yes, it's 30 seconds:

`new OkHttpClient.Builder()
  .connectTimeout(20, SECONDS)
  .readTimeout(30, SECONDS)`

**Comment by jimshowalter** [comment] 2024-03-13 19:35
Just now:

`[2024-03-13T19:26:34.945Z] INFO: Got vulns for dependencies in 8806ms
[2024-03-13T19:26:34.945Z] INFO: Fetched vulns for 500 dependencies in 8811ms
[2024-03-13T19:26:44.902Z] Exception in thread "main" com.foo.vulns.finder.VulnsFinderException: Unable to get vulns for dependencies in 10034ms: api.osv.dev: Name or service not known
[2024-03-13T19:26:44.902Z] 	at com.foo.vulns.finder.osv.OsvApiUtils.getResponse(OsvApiUtils.java:203)
[2024-03-13T19:26:44.902Z] 	at com.foo.vulns.finder.osv.OsvApiUtils.fetchImpl(OsvApiUtils.java:234)
[2024-03-13T19:26:44.902Z] 	at com.foo.vulns.finder.osv.OsvApiUtils.fetchVulnsOnePage(OsvApiUtils.java:251)
[2024-03-13T19:26:44.902Z] 	at com.foo.vulns.finder.osv.DefaultVulnsFetcher.fetchOnePage(DefaultVulnsFetcher.java:14)
[2024-03-13T19:26:44.902Z] 	at com.foo.vulns.finder.osv.OsvApiUtils.fetchVulns(OsvApiUtils.java:293)
[2024-03-13T19:26:44.902Z] 	at com.foo.vulns.finder.osv.OsvApiUtils.fetchVulns(OsvApiUtils.java:318)
[2024-03-13T19:26:44.902Z] 	at com.foo.vulns.finder.VulnsFinderMainUtils.runAllWithApiCall(VulnsFinderMainUtils.java:24)
[2024-03-13T19:26:44.902Z] 	at com.foo.vulns.finder.VulnsFinderMainUtils.runAll(VulnsFinderMainUtils.java:57)
[2024-03-13T19:26:44.902Z] 	at com.foo.vulns.finder.MainUtils.visit(MainUtils.java:38)
[2024-03-13T19:26:44.902Z] 	at com.foo.vulns.finder.MainUtils.visit(MainUtils.java:43)
[2024-03-13T19:26:44.902Z] 	at com.foo.vulns.finder.MainUtils.visit(MainUtils.java:43)
[2024-03-13T19:26:44.902Z] 	at com.foo.vulns.finder.MainUtils.mainImpl(MainUtils.java:58)
[2024-03-13T19:26:44.902Z] 	at com.foo.vulns.finder.parity.ParityCheckerUtils.checkParity(ParityCheckerUtils.java:322)
[2024-03-13T19:26:44.902Z] 	at com.foo.vulns.finder.parity.ParityChecker.main(ParityChecker.java:35)
[2024-03-13T19:26:44.902Z] Caused by: java.net.UnknownHostException: api.osv.dev: Name or service not known`

**Comment by oliverchang** [comment] 2024-03-13 22:19
Hi @jimshowalter , that latest trace looks like it might be some transitive issue resulting from your DNS resolver? Would it be possible for you to add retries on your end to mitigate that?

**Comment by jimshowalter** [comment] 2024-03-13 22:23
Agreed, and yes.

**Comment by jimshowalter** [comment] 2024-03-13 22:26
In fact, I just learned we had a DNS latency problem.

**Comment by oliverchang** [comment] 2024-03-13 22:38
I'll close this issue for now, given that we've largely mitigated the timeouts we were seeing.

**Closed by oliverchang** 2024-03-13 22:38 UTC
Labels: bug, api, under-investigation
