### ISSUE TITLE
Safely mark deleted Git entries as INVALID/withdrawn (and correctly handle undeletion)

### ISSUE THREAD

**Issue by andrewpollock** [google/osv.dev#2113] opened 2024-04-15 23:28 UTC
There are expected situations where records in Git will be deleted, e.g. https://github.com/bitnami/vulndb/issues/336#issuecomment-2049354939

https://github.com/google/osv.dev/pull/829 completely removed the behaviour of marking deleted Git entries as invalid, as a reaction to an upstream defect that caused all records for that source to temporarily disappear.

a) Revert https://github.com/google/osv.dev/pull/829, and add guardrails to refuse to process a source with more than (say) 10% of the records disappearing. This would have prevented what happened that caused #829 to be created. Refer to the guardrails as added as part of #2030 for inspiration

b) Ensure the importer can correctly transition an existing deleted and withdrawn Bug back to a non-withdrawn state if it gets undeleted.

**Comment by oliverchang** [comment] 2024-06-07 03:47
I believe this is a dupe of https://github.com/google/osv.dev/issues/2101?

**Closed by oliverchang** 2024-06-07 03:47 UTC
